import { Alarm } from '../types/Alarm';

export const ALARM_LIST: Alarm[] = [
  {
    id: 0,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '새 배지 획득!',
    content: "축하합니다! '첫 꿀 받기' 배지를 획득했습니다.",
    date: '11.16',
    isRead: false,
  },
  {
    id: 1,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '출석 완료',
    content: '오늘도 잊지 않고 출석하셨네요! 출석 5회를 달성하셨습니다.',
    date: '11.15',
    isRead: false,
  },
  {
    id: 2,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '꿀 받기 알림',
    content: '친구로부터 꿀 3개를 받았습니다. 확인해 보세요!',
    date: '11.14',
    isRead: false,
  },
  {
    id: 3,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '이벤트 참여 완료',
    content: '꿀도장 1판 이벤트에 참여해 주셔서 감사합니다.',
    date: '11.13',
    isRead: true,
  },
  {
    id: 4,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '출석 보상 지급',
    content: '누적 출석 30회를 달성하여 보상을 획득했습니다!',
    date: '11.12',
    isRead: true,
  },
  {
    id: 5,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '꿀 보내기 알림',
    content: '당신의 꿀을 받은 친구가 감사 메시지를 보냈습니다.',
    date: '11.11',
    isRead: true,
  },
  {
    id: 6,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '배지 도전!',
    content: "'꿀부자' 배지를 획득하려면 꿀을 50회 더 받아보세요.",
    date: '11.10',
    isRead: true,
  },
  {
    id: 7,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '새 알림 도착',
    content: '새로운 공지사항이 있습니다. 확인해 보세요!',
    date: '11.09',
    isRead: true,
  },
  {
    id: 8,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '업데이트 완료',
    content: '앱이 최신 버전으로 업데이트되었습니다.',
    date: '11.08',
    isRead: true,
  },
  {
    id: 9,
    image: '/assets/images/announcement/img-alarm.svg',
    title: '꿀 이벤트',
    content: '꿀도장 이벤트에 참여하고 특별한 보상을 받아보세요!',
    date: '11.07',
    isRead: true,
  },
];
